spring:
  application:
    name: campushub
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: false
  max-login-count: 3
  overflow-logout-mode: REPLACED
  is-read-header: true
  is-write-header: true
  token-style: uuid
  is-log: true
